//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public int TreatmentID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateIssued { get; set; }
    
        public virtual Treatment Treatment { get; set; }
    }
}
