//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicode
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicodeEntities : DbContext
    {
        public MedicodeEntities()
            : base("name=MedicodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorContact> DoctorContacts { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientContact> PatientContacts { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<UpcomingAppointment> UpcomingAppointments { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
