//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionID { get; set; }
        public int DoctorID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public string Medication { get; set; }
        public string Dosage { get; set; }
        public string Notes { get; set; }
        public Nullable<int> AppointmentID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
}
